quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/cliente_db
quarkus.datasource.username=cliente_user
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:secure_password_cliente}
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.flyway.migrate-at-start=true
quarkus.http.port=8081
